@token = {{$dotenv REAKTOR_TOKEN}}
@apiBase = {{$dotenv API_BASE}}

### Get SSE live matches
GET {{apiBase}}/live
Authorization: Bearer {{token}}
### Get match history and cursor for pagination
GET {{apiBase}}/history
Authorization: Bearer {{token}}
### Get the last matches from history
GET {{apiBase}}/history?cursor=NSesIWL-MpA3
Authorization: Bearer {{token}}
